### ISSUE TITLE
The biomes example is broken

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#103]
This could be caused by a multitude of issues. Further investigation needed.

**Comment by Sekky61** [comment]
So, I found that with 8 biomes, it works well, with >8 it does not.

If I understand correctly, when adding the 9th biome to Indirect `PalettedContainer`, it is no longer correct, because according to [wiki.vg](https://wiki.vg/Chunk_Format#Paletted_Container_structure), biome threshold is 3 bits.

As of now, upgrade to direct `PalettedContainer` happens when adding to indirect palette fails and it only fails after 16 pushes (because of `try_push` on `ArrayVec<T, 16>`).

There is also a TODO in `Encode for PalettedContainer`
```rust
// TODO: if bits_per_entry > MAX_INDIRECT_BITS, encode as direct.
debug_assert!(bits_per_entry <= T::MAX_INDIRECT_BITS);
```

So either we can copy Minecraft design and add check to upgrade from indirect to direct sooner, or we can implement this TODO and only encode it as direct.

**Comment by rj00a** [comment]
Thanks for finding this. I've solved the problem by implementing the TODO. However, I discovered that the `direct_bits` for biomes changes dynamically depending on the number of biomes that were registered. I've had to change the paletted container interface to account for this.
