### ISSUE TITLE
Funky inventory

### ISSUE THREAD

**Issue by EmperialDev** [valence-rs/valence#133]
When you try to use the creative inventory in the building example, it is a bit funky.

https://user-images.githubusercontent.com/98261860/197361746-e664b6ad-0228-47a5-bcce-eb76e45d9a6b.mp4

The items disapear when you click them, but if you took an item from the creative menu it doesn't go away when you close the inventory.

And I didn't show it in the video, but the search menu doesn't work when you try to search.

**Comment by dyc3** [comment]
The items disappearing when you click them from your hotbar are because creative mode intentionally doesn't track item movements, it purely operates by sending packets to set slots to have contents using `SetCreativeModeSlot`. When you pick up the item, the server sees your inventory change, marks it dirty, and flushes it to your client. This includes `carried_item`, which is never set in creative mode because the client doesn't send packets for it.

Similarly, when you pick something up from the creative menu and close the window without placing it in your hotbar, `carried_item` is was never set, so the server never sends the packet to clear our your clear your carried item.

**Comment by dyc3** [comment]
Also, I'm unable to reproduce the creative search not working. The client doesn't send any packets to do that I'm pretty sure its all client side.
