### ISSUE TITLE
Centralize packets

### ISSUE THREAD

**Issue by pepperoni21** [valence-rs/valence#400]
## Describe the problem related to your feature request.

Currently, each module defines its own packets. Even though this approach has some advantages, I think the fact that nothing binds them together is a problem. Also, packets are constant structures of the same "type" so it could make more sense to store all of them at the same location.

We can see that the [way](https://github.com/valence-rs/valence/blob/main/tools/packet_inspector/build.rs) it is done in the packet inspector is not ideal at all, and this could be avoided. Being myself trying to build a server proxy using Valence, I really don't want to use this kind of workarounds.

## What solution would you like?

We could create a `valence_packet` where we can store all the packets, or directly in the [valence_network](https://github.com/valence-rs/valence/tree/main/crates/valence_network) crate. I'm not sure how it would work and I will be happy to discuss it but I've seen that it used to work like this before so it should not be very hard to restore it.

Something like a packet registry where we could get packets by their side or their id seems good to me.

It could also allow to restore `S2cPlayPacket` and `C2sPlayPacket` which used to be very useful (even though they were probably removed for a good reason).

**Comment by rj00a** [comment]
I'm in favor of this. I originally put the packets in separate crates because of concerns about potential circular dependencies and code repetition, but in practice I don't think it's really a problem. Here's what should happen:
- Move all packets to new `valence_packet` crate (which depends on `valence_core`). Each packet gets a separate module like it existed prior to #335.
- Move `Packet` trait, `packet_id` module, packet encoder and decoders to `valence_packet`.
- Create a "packet registry" with all the vanilla packets added to it by default.
- Update the packet inspector to use the packet registry instead of the build script hack.

I'm mostly against reintroducing the packet enums like `S2cPlayPacket` and `C2sPlayPacket` for a few reasons:
- Complicates the `Packet` trait in order to support them.
- Difficult to use when lifetimes are involved (You end up having to serialize it anyway in order to transport it anywhere).
- The set of packets is meant to be open for extension (to support modded environments potentially), but enums are closed.
- Probably not very efficient with the size of the enum being the size of the largest variant.

**Comment by pepperoni21** [comment]
Fine that makes sense. I'd like to work on this, unless someone else wants to do it.

**Comment by dyc3** [comment]
Go for it :)

**Comment by pepperoni21** [comment]
Great. As I was gathering all the packets I realized that it might be problematic to use a `valence_packet` crate that depends on `valence_core` because `valence_core` also needs to depend on `valence_packet` through the protocol module. Maybe we can make a packet module inside `valence_core` instead?

**Comment by rj00a** [comment]
What parts of `valence_core` would need to depend on `valence_packet`?

**Comment by pepperoni21** [comment]
> What parts of `valence_core` would need to depend on `valence_packet`?

The protocol module that uses the Packet trait and `valence_core_macros`

**Comment by rj00a** [comment]
That's why I suggested moving those parts of the protocol module to `valence_packet`. The packet encoders, packet decoders, and `Packet` trait should all live in `valence_packet`. Then there could also be `valence_packet_macros` for the `Packet` proc macro. Don't think there will be any circular dependencies at that point.

**Comment by pepperoni21** [comment]
Actually I did but some structs are used both for packets and components/events. For example `PlayerInteractEntityC2s` needs `EntityInteraction` which is also used by `InteractEntityEvent`. And importing `valence_client` in `valence_packet` will also cause circular dependencies.

**Comment by rj00a** [comment]
`EntityInteraction` should be defined in the module where `PlayerInteractEntityC2s` is defined because it's part of the packet. Then it can be imported from `valence_client`.

**Comment by pepperoni21** [comment]
> `EntityInteraction` should be defined in the module where `PlayerInteractEntityC2s` is defined because it's part of the packet. Then it can be imported from `valence_client`.

Alright

**Comment by xGab0** [comment]
@pepperoni21 how is it going? I wanted to work on that too

**Comment by pepperoni21** [comment]
> @pepperoni21 how is it going? I wanted to work on that too

Hey, I just need to complete the packet registry now, but I went on vacation 2 weeks ago and I won't be back home for another 3 weeks. I can still work on it, but not as much as I had initially planned. That's my bad, I didn't expect to be away for such a long time. So, if you're willing to work on it, feel free to do so!
